name: riley-robot-ros2
version: '0.1'
summary: Differential drive Robot for ROS2
description: |
  This is an example ofa robot for ROS2 that uses differential drive.
  It was created by TheConstruct to have a bareminimum example of a robot
  simulation fro ROS2.

base: core20
confinement: devmode

parts:
  ros-demos:
    plugin: colcon
    source: https://bitbucket.org/theconstructcore/box_bot.git
    source-branch: foxy
    build-packages: [make, gcc, g++]
    stage-packages: [ros-foxy-gazebo-ros-pkgs, ros-foxy-ros2launch, ros-foxy-urdf, libatlas-base-dev]
    override-build: |
      snapcraftctl build
      set -ex
      for dir in $SNAPCRAFT_PART_INSTALL/usr/lib/*/; do
          (cd $dir;
          if [ -f blas/libblas.so.3.* ]; then
              ln -s blas/libblas.so.3.* libblas.so.3
          fi)
      done


apps:
  riley-robot-ros2-sim:
    command: opt/ros/foxy/bin/ros2 launch my_riley_robot_launcher riley_robot_launch.py
    environment:      
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/atlas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    extensions: [ros2-foxy]
